### ISSUE TITLE
Liste tam görünmüyor

### ISSUE THREAD

**Issue by tolgahanuzun** [apoStyLEE/vueaudioplayer#1]
13 inç ekran - Google Chrome ile girdiğimde 12. podcast hiç görünmüyor. 11 podcast'de yarim kalıyor. Şöyle;

![](https://i.hizliresim.com/lb2g4p.png)

**Comment by apoStyLEE** [comment]
la olm bismillah :D

**Comment by tolgahanuzun** [comment]
@gurkanyarar sağolsun abi gördüğüm herşeyi test edesim geliyor 😅

**Comment by apoStyLEE** [comment]
güzel güzel, ilerleyen zamanlarda birlikte güzel şeyler yapabiliriz, her şeyi öğrenin :)

**Comment by omrumbakitemiz** [comment]
13 inç - Safari - normal çözünürlük(1280x800) aynı sorun

<img width="484" alt="screen shot 2017-09-21 at 13 50 48" src="https://user-images.githubusercontent.com/12871066/30692366-e99f6150-9ed3-11e7-942f-9ba7776691c6.png">

**Comment by apoStyLEE** [comment]
Düzelttim problemi.
